todasCartas = [
    { nome: "Asparagus", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-asparagus.jpeg" },
    { nome: "Avocado", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-avocado.jpeg" },
    { nome: "Beans", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-beans.jpeg" },
    { nome: "Beats", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-beats.jpeg" },
    { nome: "Broccoli", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-broccoli.jpeg" },
    { nome: "Cabbage", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-cabbage.jpeg" },
    { nome: "Carrot", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-carrot.jpeg" },
    { nome: "Cauliflower", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-cauliflower.jpeg" },
    { nome: "Chilli", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-chilli.jpeg" },
    { nome: "Corn", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-corn.jpeg" },
    { nome: "Cucumber", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-cucumber.jpeg" },
    { nome: "Eggplant", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-eggplant.jpeg" },
    { nome: "Garlic", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-garlic.jpeg" },
    { nome: "Leek", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-leek.jpeg" },
    { nome: "Lettuce", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-lettuce.jpeg" },
    { nome: "Mushroom", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-mushroom.jpeg" },
    { nome: "Onion", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-onion.jpeg" },
    { nome: "Pepper", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-pepper.jpeg" },
    { nome: "Pickle", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-pickle.jpeg" },
    { nome: "Potato", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-potato.jpeg" },
    { nome: "Pumpkin", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-pumpkin.jpeg" },
    { nome: "Raddish", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-raddish.jpeg" },
    { nome: "Spinach", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-spinach.jpeg" },
    { nome: "Sproats", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-sproats.jpeg" },
    { nome: "Sweet Potato", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-sweet-potato.jpeg" },
    { nome: "Tomato", link: "../images/VEGETABLE-FLASHCARDS/vegetable-flashcard-tomato.jpeg" },
    { nome: "Lizard", link: "../images/flashcards/Jungle-animal-Lizard-flashcard.jpeg" },
    { nome: "Anteater", link: "../images/flashcards/Jungle-animal--anteater-flashcard.jpeg" },
    { nome: "Bat", link: "../images/flashcards/Jungle-animal--bat-flashcard.jpeg" },
    { nome: "Flamingo", link: "../images/flashcards/Jungle-animal--flamingo-flashcard.jpeg" },
    { nome: "Monkey", link: "../images/flashcards/Jungle-animal-monkey-flashcard.jpeg" },
    { nome: "Gorilla", link: "../images/flashcards/Jungle-animal--gorilla-flashcard.jpeg" },
    { nome: "Parrot", link: "../images/flashcards/Jungle-animal-parrot-flashcard.jpeg" },
    { nome: "Panda", link: "../images/flashcards/Jungle-animal-panda-flashcard.jpeg" },
    { nome: "Sloth", link: "../images/flashcards/Jungle-animal-sloth-flashcard.jpeg" },
    { nome: "Snake", link: "../images/flashcards/Jungle-animal-snake-flashcard.jpeg" },
    {nome: "Tiger", link:"../images/flashcards/Jungle-animal-tiger-flashcard.jpeg"},
    {nome: "Iguana", link:"../images/flashcards/Jungle-animal--iguana-flashcard.jpeg"},
    {nome: "Peacock", link:"../images/flashcards/Jungle-animal-peacock-flashcard.jpeg"},
    {nome: "Toucan", link:"../images/flashcards/Jungle-animal-toucan-flashcard.jpeg"},
    { nome: "American Football", link: "../images/SPORTS flashcards/sports flashcards American-Football.jpeg" },
    { nome: "Archery", link: "../images/SPORTS flashcards/sports flashcards archery.jpeg" },
    { nome: "Badminton", link: "../images/SPORTS flashcards/sports flashcards badminton.jpeg" },
    { nome: "Baseball", link: "../images/SPORTS flashcards/sports flashcards baseball.jpeg" },
    { nome: "Basketball", link: "../images/SPORTS flashcards/sports flashcards basketball.jpeg" },
    { nome: "Bowling", link: "../images/SPORTS flashcards/sports flashcards bowling.jpeg" },
    { nome: "Boxing", link: "../images/SPORTS flashcards/sports flashcards boxing.jpeg" },
    { nome: "Cricket", link: "../images/SPORTS flashcards/sports flashcards cricket.jpeg" },
    { nome: "Cycling", link: "../images/SPORTS flashcards/sports flashcards cycling.jpeg" },
    { nome: "Darts", link: "../images/SPORTS flashcards/sports flashcards darts.jpeg" },
    { nome: "Fencing", link: "../images/SPORTS flashcards/sports flashcards fencing.jpeg" },
    { nome: "Fishing", link: "../images/SPORTS flashcards/sports flashcards fishing.jpeg" },
    { nome: "Football (Soccer)", link: "../images/SPORTS flashcards/sports flashcards football-(soccer).jpeg" },
    { nome: "Football", link: "../images/SPORTS flashcards/sports flashcards football.jpeg" },
    { nome: "Golf", link: "../images/SPORTS flashcards/sports flashcards golf.jpeg" },
    { nome: "Ice Hockey", link: "../images/SPORTS flashcards/sports flashcards ice-hockey.jpeg" },
    { nome: "Ice Skating", link: "../images/SPORTS flashcards/sports flashcards ice-skating.jpeg" },
    { nome: "Inline Skating", link: "../images/SPORTS flashcards/sports flashcards inline-skating.jpeg" },
    { nome: "Judo", link: "../images/SPORTS flashcards/sports flashcards judo.jpeg" },
    { nome: "Karate", link: "../images/SPORTS flashcards/sports flashcards karate.jpeg" },
    { nome: "Pool", link: "../images/SPORTS flashcards/sports flashcards pool.jpeg" },
    { nome: "Rock Climbing", link: "../images/SPORTS flashcards/sports flashcards rock-climbing.jpeg" },
    { nome: "Rowing", link: "../images/SPORTS flashcards/sports flashcards rowing.jpeg" },
    { nome: "Rugby", link: "../images/SPORTS flashcards/sports flashcards rugby.jpeg" },
    { nome: "Sailing", link: "../images/SPORTS flashcards/sports flashcards sailing.jpeg" },
    { nome: "Show Jumping", link: "../images/SPORTS flashcards/sports flashcards show-jumping.jpeg" },
    { nome: "Skating", link: "../images/SPORTS flashcards/sports flashcards skating.jpeg" },
    { nome: "Skiing", link: "../images/SPORTS flashcards/sports flashcards skiing.jpeg" },
    { nome: "Snowboarding", link: "../images/SPORTS flashcards/sports flashcards snowboarding.jpeg" },
    { nome: "Soccer", link: "../images/SPORTS flashcards/sports flashcards soccer.jpeg" },
    { nome: "Surfing", link: "../images/SPORTS flashcards/sports flashcards surfing.jpeg" },
    { nome: "Swimming", link: "../images/SPORTS flashcards/sports flashcards swimming.jpeg" },
    { nome: "Table Tennis", link: "../images/SPORTS flashcards/sports flashcards table-tennis.jpeg" },
    { nome: "Tennis", link: "../images/SPORTS flashcards/sports flashcards tennis.jpeg" },
    { nome: "Volleyball", link: "../images/SPORTS flashcards/sports flashcards volleyball.jpeg" },
    { nome: "Wrestling", link: "../images/SPORTS flashcards/sports flashcards wrestling.jpeg" },
    { nome: "Pteranodon", link: "../images/DINOSAUR flashcards/Pteranodon.jpeg" },
    { nome: "Spinosaurus", link: "../images/DINOSAUR flashcards/Spinosaurus.jpeg" },
    { nome: "Stegosaurus", link: "../images/DINOSAUR flashcards/Stegosaurus.jpeg" },
    { nome: "T-Rex", link: "../images/DINOSAUR flashcards/T-Rex.jpeg" },
    { nome: "Triceratops", link: "../images/DINOSAUR flashcards/Triceratops.jpeg" },
    { nome: "Velociraptor", link: "../images/DINOSAUR flashcards/Velociraptor.jpeg" },
    { nome: "Allosaurus", link: "../images/DINOSAUR flashcards/Allosaurus.jpeg" },
    { nome: "Ankylosaurus", link: "../images/DINOSAUR flashcards/Ankylosaurus.jpeg" },
    { nome: "Apatosaurus", link: "../images/DINOSAUR flashcards/Apatosaurus.jpeg" },
    { nome: "Archaeopteryx", link: "../images/DINOSAUR flashcards/Archaeopteryx.jpeg" },
    { nome: "Brachiosaurus", link: "../images/DINOSAUR flashcards/Brachiosaurus.jpeg" },
    { nome: "Brontosaurus", link: "../images/DINOSAUR flashcards/Brontosaurus.jpeg" },
    { nome: "Coelophysis", link: "../images/DINOSAUR flashcards/Coelophysis.jpeg" },
    { nome: "Dilophosaurus", link: "../images/DINOSAUR flashcards/Dilophosaurus.jpeg" },
    { nome: "Elasmosaurus", link: "../images/DINOSAUR flashcards/Elasmosaurus.jpeg" },
    { nome: "Parasaurolophus", link: "../images/DINOSAUR flashcards/parasaurolophus.jpeg" },
    { nome: "Christmas Hat", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Christmas-hat.jpeg" },
    { nome: "Christmas Lights", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Christmas-lights.jpeg" },
    { nome: "Christmas Pudding", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Christmas-pudding.jpeg" },
    { nome: "Christmas Tree", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Christmas-tree.jpeg" },
    { nome: "Crackers", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-crackers.jpeg" },
    { nome: "Decorations", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-decorations.jpeg" },
    { nome: "Elf", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-elf.jpeg" },
    { nome: "Fireplace", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-fireplace.jpeg" },
    { nome: "Gingerbread Man", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-gingerbread-man.jpeg" },
    { nome: "Holly", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-holly.jpeg" },
    { nome: "Mince Pies", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-mince-pies.jpeg" },
    { nome: "Mistletoe", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-mistletoe.jpeg" },
    { nome: "Mittens", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-mittens.jpeg" },
    { nome: "Mrs. Claus", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Mrs.-Claus.jpeg" },
    { nome: "Penguin", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-penguin.jpeg" },
    { nome: "Polar Bear", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-polar-bear.jpeg" },
    { nome: "Presents", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-presents.jpeg" },
    { nome: "Reindeer", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-reindeer.jpeg" },
    { nome: "Rudolf", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Rudolf.jpeg" },
    { nome: "Santa", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Santa.jpeg" },
    { nome: "Santa's Grotto", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Santa's-Grotto.jpeg" },
    { nome: "Sleigh", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-sleigh.jpeg" },
    { nome: "Snowflake", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-snowflake.jpeg" },
    { nome: "Snowglobe", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-snowglobe.jpeg" },
    { nome: "Snowman", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-snowman.jpeg" },
    { nome: "Star", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-star.jpeg" },
    { nome: "Stocking", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-stocking.jpeg" },
    { nome: "Toys", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-toys.jpeg" },
    { nome: "Turkey", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-turkey.jpeg" },
    { nome: "Wreath", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-wreath.jpeg" },
    { nome: "Bells", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-bells.jpeg" },
    { nome: "Candle", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-candle.jpeg" },
    { nome: "Candy Cane", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-candy-cane.jpeg" },
    { nome: "Chimney", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-chimney.jpeg" },
    { nome: "Christmas", link: "../images/CHRISTMAS flashcards/Christmas-flashcards-Christmas.jpeg" },
    { nome: "Skull", link: "../images/halloween flashcards/skull-flashcard.jpeg" },
    { nome: "Spider", link: "../images/halloween flashcards/spider-flashcards.jpeg" },
    { nome: "Spider Web", link: "../images/halloween flashcards/spider-web-flashcard.jpeg" },
    { nome: "Vampire", link: "../images/halloween flashcards/vampire-flashcard.jpeg" },
    { nome: "Voodoo Doll", link: "../images/halloween flashcards/voodoo-doll-flashcard.jpeg" },
    { nome: "Werewolf", link: "../images/halloween flashcards/werewolf-flashcard.jpeg" },
    { nome: "Witch", link: "../images/halloween flashcards/witch-flashcard.jpeg" },
    { nome: "Zombie", link: "../images/halloween flashcards/zombie-flashcard.jpeg" },
    { nome: "Bat", link: "../images/halloween flashcards/bat-flashcard.jpeg" },
    { nome: "Black Cat", link: "../images/halloween flashcards/black-cat-flashcard.jpeg" },
    { nome: "Candle", link: "../images/halloween flashcards/candle-flashcard.jpeg" },
    { nome: "Candy", link: "../images/halloween flashcards/candy-flashcard.jpeg" },
    { nome: "Cauldron", link: "../images/halloween flashcards/cauldron-flashcard.jpeg" },
    { nome: "Coffin", link: "../images/halloween flashcards/coffin-flashcard.jpeg" },
    { nome: "Crow", link: "../images/halloween flashcards/crow-flashcards.jpeg" },
    { nome: "Death", link: "../images/halloween flashcards/death-flashcard.jpeg" },
    { nome: "Devil", link: "../images/halloween flashcards/devil-flashcard.jpeg" },
    { nome: "Frankenstein", link: "../images/halloween flashcards/Frankenstein-flashcard.jpeg" },
    { nome: "Ghost", link: "../images/halloween flashcards/ghost-flashcard.jpeg" },
    { nome: "Grave", link: "../images/halloween flashcards/grave-flashcard.jpeg" },
    { nome: "Haunted House", link: "../images/halloween flashcards/haunted-house.jpeg" },
    { nome: "Invisible Man", link: "../images/halloween flashcards/invisible-man-flashcard.jpeg" },
    { nome: "Monster", link: "../images/halloween flashcards/monster-flashcard.jpeg" },
    { nome: "Moon", link: "../images/halloween flashcards/moon-flashcard.jpeg" },
    { nome: "Mummy", link: "../images/halloween flashcards/mummy-flashcard.jpeg" },
    { nome: "Pumpkin", link: "../images/halloween flashcards/pumpkin-flashcard.jpeg" },
    { nome: "Pumpkin Pie", link: "../images/halloween flashcards/pumpkin-pie-flashcard.jpeg" },
    { nome: "Skeleton", link: "../images/halloween flashcards/skeleton-flashcard.jpeg" },
    { nome: "Rain", link: "../images/PLANT flashcards/plant-flashcards-rain.jpeg" },
    { nome: "Roots", link: "../images/PLANT flashcards/plant-flashcards-roots.jpeg" },
    { nome: "Seed", link: "../images/PLANT flashcards/plant-flashcards-seed.jpeg" },
    { nome: "Seeds", link: "../images/PLANT flashcards/plant-flashcards-seeds.jpeg" },
    { nome: "Soil", link: "../images/PLANT flashcards/plant-flashcards-soil.jpeg" },
    { nome: "Sprout", link: "../images/PLANT flashcards/plant-flashcards-sprout.jpeg" },
    { nome: "Stem", link: "../images/PLANT flashcards/plant-flashcards-stem.jpeg" },
    { nome: "Sun", link: "../images/PLANT flashcards/plant-flashcards-sun.jpeg" },
    { nome: "Tree", link: "../images/PLANT flashcards/plant-flashcards-tree.jpeg" },
    { nome: "Tree Leaves", link: "../images/PLANT flashcards/plant-flashcards-tree-leaves.jpeg" },
    { nome: "Tree Roots", link: "../images/PLANT flashcards/plant-flashcards-tree-roots.jpeg" },
    { nome: "Trunk", link: "../images/PLANT flashcards/plant-flashcards-trunk.jpeg" },
    { nome: "Wind", link: "../images/PLANT flashcards/plant-flashcards-wind.jpeg" },
    { nome: "Bark", link: "../images/PLANT flashcards/plant-flashcards-bark.jpeg" },
    { nome: "Branch", link: "../images/PLANT flashcards/plant-flashcards-branch.jpeg" },
    { nome: "Bush", link: "../images/PLANT flashcards/plant-flashcards-bush.jpeg" },
    { nome: "Flower", link: "../images/PLANT flashcards/plant-flashcards-flower.jpeg" },
    { nome: "Garden", link: "../images/PLANT flashcards/plant-flashcards-garden.jpeg" },
    { nome: "Leaves", link: "../images/PLANT flashcards/plant-flashcards-leaves.jpeg" },
    { nome: "Petal", link: "../images/PLANT flashcards/plant-flashcards-petal.jpeg" },
    { nome: "Petals", link: "../images/PLANT flashcards/plant-flashcards-petals.jpeg" },
    { nome: "Happy Boy", link: "../images/Feelings flashcards/happy-boy.jpeg" },
    { nome: "Happy Girl", link: "../images/Feelings flashcards/happy-girl.jpeg" },
    { nome: "Hungry Boy", link: "../images/Feelings flashcards/hungry-boy.jpeg" },
    { nome: "Hungry Girl", link: "../images/Feelings flashcards/hungry-girl.jpeg" },
    { nome: "Sad Boy", link: "../images/Feelings flashcards/sad-boy.jpeg" },
    { nome: "Sad Girl", link: "../images/Feelings flashcards/sad-girl.jpeg" },
    { nome: "Scared Boy", link: "../images/Feelings flashcards/scared-boy.jpeg" },
    { nome: "Scared Girl", link: "../images/Feelings flashcards/scared-girl.jpeg" },
    { nome: "Thirsty Boy", link: "../images/Feelings flashcards/thirsty-boy.jpeg" },
    { nome: "Thirsty Girl", link: "../images/Feelings flashcards/thirsty-girl.jpeg" },
    { nome: "Tired Boy", link: "../images/Feelings flashcards/tired-boy.jpeg" },
    { nome: "Tired Girl", link: "../images/Feelings flashcards/tired-girl.jpeg" },
    { nome: "Angry Boy", link: "../images/Feelings flashcards/angry-boy.jpeg" },
    { nome: "Angry Girl", link: "../images/Feelings flashcards/angry-girl.jpeg" },
    { nome: "Blank Boy", link: "../images/Feelings flashcards/blank-boy.jpeg" },
    { nome: "Blank Girl", link: "../images/Feelings flashcards/blank-girl.jpeg" },
    { nome: "Toothache", link: "../images/HEALTH flashcards/health-flashcards-toothache.jpeg" },
    { nome: "Asthma", link: "../images/HEALTH flashcards/health-flashcards-asthma.jpeg" },
    { nome: "Backache", link: "../images/HEALTH flashcards/health-flashcards-backache.jpeg" },
    { nome: "Broken Arm", link: "../images/HEALTH flashcards/health-flashcards-broken-arm.jpeg" },
    { nome: "Broken Leg", link: "../images/HEALTH flashcards/health-flashcards-broken-leg.jpeg" },
    { nome: "Cold", link: "../images/HEALTH flashcards/health-flashcards-cold.jpeg" },
    { nome: "Cough", link: "../images/HEALTH flashcards/health-flashcards-cough.jpeg" },
    { nome: "Cut", link: "../images/HEALTH flashcards/health-flashcards-cut.jpeg" },
    { nome: "Earache", link: "../images/HEALTH flashcards/health-flashcards-earache.jpeg" },
    { nome: "Fever", link: "../images/HEALTH flashcards/health-flashcards-fever.jpeg" },
    { nome: "Headache", link: "../images/HEALTH flashcards/health-flashcards-headache.jpeg" },
    { nome: "Nosebleed", link: "../images/HEALTH flashcards/health-flashcards-nosebleed.jpeg" },
    { nome: "Rash", link: "../images/HEALTH flashcards/health-flashcards-rash.jpeg" },
    { nome: "Runny Nose", link: "../images/HEALTH flashcards/health-flashcards-runny-nose.jpeg" },
    { nome: "Sneeze", link: "../images/HEALTH flashcards/health-flashcards-sneeze.jpeg" },
    { nome: "Sore Throat", link: "../images/HEALTH flashcards/health-flashcards-sore-throat.jpeg" },
    { nome: "Stomach Ache", link: "../images/HEALTH flashcards/health-flashcards-stomach-ache.jpeg" },
    { nome: "Sunburn", link: "../images/HEALTH flashcards/health-flashcards-sun-burn.jpeg" }

]